<?php

namespace tdt4237\webapp;

use Symfony\Component\Config\Definition\Exception\Exception;

class Hash
{

    public function __construct()
    {
    }

    public static function make($plaintext)
    {

        $options = [
            'cost' => 12,
        ];

        #uses php5.5's new bcrypt function, with a cost of 12 (higher than normal)
        #salt is auto-generated by /udev/random, and stored alongside the passhash
        return password_hash($plaintext, PASSWORD_DEFAULT, $options);

    }

    public function check($plaintext, $hash)
    {
        return password_verify($plaintext,$hash);
    }

}
